name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Visit Every 10 minutes to prevent spin down in free version Render live link
  workflow_dispatch: # Allow manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render URL
        run: curl -s -o /dev/null https://study-room-booking.onrender.com
